services:
  audiobookshelf:
      image: ghcr.io/advplyr/audiobookshelf:latest
      container_name: audiobook-shelf
      ports:
        - $AUDIOBOOKSHELF_PORT:80
      volumes:
        - /home/red/external-drives/Storage/Books/Applied Science:/applied_science-books
        - /home/red/external-drives/Storage/Books/Art:/art-books
        - /home/red/external-drives/Storage/Books/Black-Library-Books:/Black-Library-Books
        - /home/red/external-drives/Storage/Books/Computer Science:/Computer_Science-books
        - /home/red/external-drives/Storage/Books/Applied Science:/books
        - /home/red/external-drives/Storage/Books/General:/General-books
        - /home/red/external-drives/Storage/Books/Novels:/Novels
        - /home/red/external-drives/Storage/Books/Sports:/Sports
        - /home/red/external-drives/Storage/Books/AudioBooks:/audio_books
        - ./audio_book_shelf_config:/config
        - ./audio_book_shelf_metadata:/metadata
      env_file:
        - .env
      environment:
        - TZ=$TIMEZONE
      deploy:
        resources:
          limits:
            memory: $AUDIOBOOKSHELF_MEMORY

volumes:
  audio_book_shelf_config:
  audio_book_shelf_metadata: